### ISSUE TITLE
build tools: Error Rebuilding esp CSP

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#192]
```
Completed: Unidad 8 Proyecto opcional: Ordenar, Página 3
/Volumes/Michael/Users/michael/Dropbox/Projects/bjc-r/utilities/build-tools/main.rb:415:in `extract_unit_path': undefined method `split' for nil:NilClass (NoMethodError)

      match = bracket_removed[1].split(/\]/).join.to_s
                                ^^^^^^
	from /Volumes/Michael/Users/michael/Dropbox/Projects/bjc-r/utilities/build-tools/main.rb:191:in `addSummariesToTopic'
	from /Volumes/Michael/Users/michael/Dropbox/Projects/bjc-r/utilities/build-tools/main.rb:462:in `block in parse_units'
	from /Volumes/Michael/Users/michael/Dropbox/Projects/bjc-r/utilities/build-tools/main.rb:459:in `each'
	from /Volumes/Michael/Users/michael/Dropbox/Projects/bjc-r/utilities/build-tools/main.rb:459:in `parse_units'
	from /Volumes/Michael/Users/michael/Dropbox/Projects/bjc-r/utilities/build-tools/main.rb:73:in `Main'
	from ./utilities/build-tools/rebuild-all.rb:26:in `<main>'

```

**Comment by cycomachead** [comment]
This must have been fixed at some point.
